name: 9HITS
on:
    # push:
    workflow_dispatch:
    # schedule:
    #   - cron: '40 0 * * *'
    # schedule:
    #     - cron: '1/2 * * * *'
    # schedule:
    #     - cron: '0 0 0/24 * * *'
        



# apt update

jobs:  
    job_9hits:
        runs-on: ubuntu-latest
        timeout-minutes: 1440
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: download
              run: |
                DIR=$(pwd)
                wget http://dl.9hits.com/3.0.4/9hitsv3-linux64.tar.bz2
                tar -xvf 9hitsv3-linux64.tar.bz2
                cd 9hitsv3-linux64
                HITS_DIR=$(pwd)
                cp -rf $DIR/9hits/config $HITS_DIR
            - name: update x
              run: |
                sudo apt-get update
                sudo apt-get install -y xvfb
                sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
                sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
                sudo apt-get -y install imagemagick x11-apps 
            - name: Dawn-install
              run: |
                cd Dawn
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            
            - name: run
              run: |
                  Xvfb -ac :99 -screen 0 1280x1024x16 &
                  export DISPLAY=:99

                  cd 9hitsv3-linux64
                  nohup ./9hits &
            - name: Dawn-run
              run: |
                cd Dawn
                source venv/bin/activate
                python main.py 
    job_9hits1:
        runs-on: ubuntu-latest
        timeout-minutes: 1440
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: download
              run: |
                DIR=$(pwd)
                wget http://dl.9hits.com/3.0.4/9hitsv3-linux64.tar.bz2
                tar -xvf 9hitsv3-linux64.tar.bz2
                cd 9hitsv3-linux64
                HITS_DIR=$(pwd)
                cp -rf $DIR/9hits/config $HITS_DIR
            - name: update x
              run: |
                sudo apt-get update
                sudo apt-get install -y xvfb
                sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
                sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
                sudo apt-get -y install imagemagick x11-apps 
            - name: Dawn-install
              run: |
                cd Dawn
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            
            - name: run
              run: |
                  Xvfb -ac :99 -screen 0 1280x1024x16 &
                  export DISPLAY=:99

                  cd 9hitsv3-linux64
                  nohup ./9hits &
            - name: Dawn-run
              run: |
                cd Dawn
                source venv/bin/activate
                python main.py 
    # job_9hits:
    #     runs-on: ubuntu-latest
    #     timeout-minutes: 1440
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: download
    #           run: |
    #             DIR=$(pwd)
    #             wget http://dl.9hits.com/3.0.4/9hitsv3-linux64.tar.bz2
    #             tar -xvf 9hitsv3-linux64.tar.bz2
    #             cd 9hitsv3-linux64
    #             HITS_DIR=$(pwd)
    #             cp -rf $DIR/9hits/config $HITS_DIR
    #         - name: update x
    #           run: |
    #             sudo apt-get update
    #             sudo apt-get install -y xvfb
    #             sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
    #             sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
    #             sudo apt-get -y install imagemagick x11-apps

                

                
    #         - name: run
    #           run: |
    #             Xvfb -ac :99 -screen 0 1280x1024x16 &
    #             export DISPLAY=:99

    #             cd 9hitsv3-linux64
    #             ./9hits
    # job_9hits1:
    #     runs-on: ubuntu-latest
    #     timeout-minutes: 1440
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: download
    #           run: |
    #             DIR=$(pwd)
    #             wget http://dl.9hits.com/3.0.4/9hitsv3-linux64.tar.bz2
    #             tar -xvf 9hitsv3-linux64.tar.bz2
    #             cd 9hitsv3-linux64
    #             HITS_DIR=$(pwd)
    #             cp -rf $DIR/9hits/config $HITS_DIR
    #         - name: update x
    #           run: |
    #             sudo apt-get update
    #             sudo apt-get install -y xvfb
    #             sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
    #             sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
    #             sudo apt-get -y install imagemagick x11-apps

                

    #         - name: run
    #           run: |
    #             Xvfb -ac :99 -screen 0 1280x1024x16 &
    #             export DISPLAY=:99

    #             cd 9hitsv3-linux64
    #             ./9hits
  
    # job_grass:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Grass-install
    #           run: |
    #             cd grass
    #             python -m venv venv
    #             source venv/bin/activate
    #             pip install -r requirements.txt
    #         - name: Grass-run
    #           run: |
    #             cd grass
    #             source venv/bin/activate
    #             python grass.py