name: GRADIENT
on:
    # push:
    workflow_dispatch:
    # schedule:
    #   - cron: '30 0 * * *'
    # schedule:
    #     - cron: '1/2 * * * *'
    # schedule:
    #     - cron: '0 0 0/24 * * *'
        

env:
    GRADIENT_USERNAME: ${{ secrets.GRADIENT_USERNAME }}
    GRADIENT_PASS: ${{ secrets.GRADIENT_PASS }}

# 1440

jobs:  
    job_gradient:
        runs-on: ubuntu-latest
        timeout-minutes: 1440
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Gradient-install
              run: |
                cd Gradient
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            - name: Gradient-run
              run: |
                cd Gradient
                source venv/bin/activate
                python main.py
    job_gradient1:
        runs-on: ubuntu-latest
        timeout-minutes: 1440
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Gradient-install
              run: |
                cd Gradient
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            - name: Gradient-run
              run: |
                cd Gradient
                source venv/bin/activate
                python main.py



    # job_grass:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Grass-install
    #           run: |
    #             cd grass
    #             python -m venv venv
    #             source venv/bin/activate
    #             pip install -r requirements.txt
    #         - name: Grass-run
    #           run: |
    #             cd grass
    #             source venv/bin/activate
    #             python grass.py